frameworkVersion: '3'

service: strava-reporter

useDotenv: true

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, "dev"}
  profile: personal
  region: us-west-2
  environment:
    ACTIVITY_TOPIC_ARN: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:service}-${self:provider.stage}-activities
    USERS_DYNAMODB_TABLE: ${self:service}-${self:provider.stage}-users
    MESSAGES_DYNAMODB_TABLE: ${self:service}-${self:provider.stage}-messages
    CLIENT_ID: "${env:CLIENT_ID}"
    CLIENT_SECRET: "${env:CLIENT_SECRET}"
    SUBSCRIPTION_ID: ${env:SUBSCRIPTION_ID}
    DISCORD_WEBHOOK_URL: ${env:DISCORD_WEBHOOK_URL}
    LAYER_ARN: ${env:LAYER_ARN}
    MAPBOX_ACCESS_TOKEN: ${env:MAPBOX_ACCESS_TOKEN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:#{AWS::Region}:*:table/${self:service}-${self:provider.stage}-*"
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: ${self:provider.environment.ACTIVITY_TOPIC_ARN}

functions:
  subscribe:
    handler: events.handler.subscribe
    events:
      - http:
          path: strava/webhook
          method: GET
  authorize-user:
    handler: auth.handler.authorize
    layers:
      - ${self:provider.environment.LAYER_ARN}
    events:
      - http:
          path: strava/authorize
          method: GET
  post-event:
    handler: events.handler.post_event
    layers:
      - ${self:provider.environment.LAYER_ARN}
    events:
      - sns:
          topicName: ${self:service}-${self:provider.stage}-activities
          displayName: New strava activity topic

resources:
  Resources:
    ApiGatewayRestMethodModel:
      Type: AWS::ApiGateway::Model
      Properties:
        ContentType: application/json
        Description: "Strava Webhook Model"
        RestApiId: { Ref: 'ApiGatewayRestApi' }
        Schema: "{\"required\":[\"subscription_id\"],\"properties\":{\"subscription_id\":{\"type\":\"number\",\"enum\":[${self:provider.environment.SUBSCRIPTION_ID}]}}}"
    ApiGatewayRequestValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: ${self:service}-${self:provider.stage}-validator
        RestApiId: { Ref: 'ApiGatewayRestApi' }
        ValidateRequestBody: true
    ApiGatewayMethodStravaWebhookPost:
      Type: AWS::ApiGateway::Method
      Properties:
        RequestValidatorId: { Ref: 'ApiGatewayRequestValidator' }
        RequestModels:
          application/json: { Ref: 'ApiGatewayRestMethodModel' }
    TokenStore:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: "${self:provider.environment.USERS_DYNAMODB_TABLE}"
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    WebhookMessages:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: "${self:provider.environment.MESSAGES_DYNAMODB_TABLE}"
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: activity_id
            AttributeType: N
        KeySchema:
          - AttributeName: activity_id
            KeyType: HASH

custom:
  apiGatewayServiceProxies:
    - sns:
        path: /strava/webhook
        method: post
        topicName: ${self:service}-${self:provider.stage}-activities
        cors: true
        response:
          - statusCode: 200

package:
  patterns:
    - '!venv/**'
    - '!requirements.txt'
    - '!tests/**'
    - '!README.md'
  individually: true

plugins:
  - serverless-pseudo-parameters
  - serverless-apigateway-service-proxy
